default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ENV["DATABASE_USERNAME"]
  password: ENV["DATABASE_PASSWORD"]
  host: localhost

development:
  <<: *default
  database: users_development

test:
  <<: *default
  database: users_test

production:
  <<: *default
  database: your_app_name_production
  username: ENV["DATABASE_USERNAME"]
  password: ENV["DATABASE_PASSWORD"]
  host: ENV["DATABASE_HOST"]
